modLoader = "javafml"
loaderVersion = "[40,)"
issueTrackerURL = "https://github.com/ValkyrienSkies/Valkyrien-Skies-2/issues"
license = "MIT License"

[[mods]]
modId = "open_waters"
version = "${version}"
displayName = "Open Waters"
authors = ["TechTastic"]
description = '''
A VS2 Addon for Sailing
'''
logoFile = "assets/open_waters/icon.png"

[[dependencies.open_waters]]
modId = "forge"
mandatory = true
versionRange = "[40.1.69,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.open_waters]]
modId = "minecraft"
mandatory = true
versionRange = "[1.18.2,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.open_waters]]
modId = "valkyrienskies"
mandatory = true
versionRange = "[${vs2_version},)"
ordering = "AFTER"
side = "BOTH"